set(_CATKIN_CURRENT_PACKAGE "opencv_aruco")
set(opencv_aruco_VERSION "0.0.0")
set(opencv_aruco_MAINTAINER "paula <paula@todo.todo>")
set(opencv_aruco_PACKAGE_FORMAT "2")
set(opencv_aruco_BUILD_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(opencv_aruco_BUILD_EXPORT_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(opencv_aruco_BUILDTOOL_DEPENDS "catkin")
set(opencv_aruco_BUILDTOOL_EXPORT_DEPENDS )
set(opencv_aruco_EXEC_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(opencv_aruco_RUN_DEPENDS "cv_bridge" "image_transport" "roscpp" "sensor_msgs" "std_msgs")
set(opencv_aruco_TEST_DEPENDS )
set(opencv_aruco_DOC_DEPENDS )
set(opencv_aruco_URL_WEBSITE "")
set(opencv_aruco_URL_BUGTRACKER "")
set(opencv_aruco_URL_REPOSITORY "")
set(opencv_aruco_DEPRECATED "")